name: Docker Image Downloader (Release Version)

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: '输入完整的 Docker 镜像名称'
        required: true
        default: 'vllm/vllm-openai:latest'

jobs:
  build:
    runs-on: ubuntu-latest
    # 给 Action 写入 Release 的权限
    permissions:
      contents: write
    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

      - name: Pull Docker Image
        run: |
          docker pull ${{ github.event.inputs.image_name }}

      - name: Save and Compress Image
        run: |
          # 生成文件名
          CLEAN_NAME=$(echo "${{ github.event.inputs.image_name }}" | sed 's/[:\/]/_/g')
          IMAGE_FILE="${CLEAN_NAME}.tar.gz"
          echo "Saving to $IMAGE_FILE ..."
          docker save ${{ github.event.inputs.image_name }} | gzip > $IMAGE_FILE
          echo "FILE_NAME=$IMAGE_FILE" >> $GITHUB_ENV
          echo "TAG_NAME=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Docker Image Release ${{ env.TAG_NAME }}
          files: ${{ env.FILE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
